# Generated by Django 4.2.7 on 2023-11-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist1', models.CharField(max_length=255)),
                ('playlist2', models.CharField(max_length=255)),
                ('similarity', models.FloatField()),
            ],
        ),
    ]
